### PR TITLE
Update to only include the initial commit branch if one is specified

### PR DESCRIPTION
**Pull request by slewis74**
Fixes the serialization to only pass the initial commit branch if one is needed/specified.

One is needed if the default branch is protected. In this case, if one isn't provided a default will be used.

Relates to OctopusDeployLabs/terraform-provider-octopusdeploy#477

### CODE REVIEW

**Review by benPearce1 — APPROVED** [review]
LGTM pending flakey tests

**Comment by benPearce1** [comment]
The `TestAPIKeyServiceDeleteByID` failing test is being fixed/removed in  https://github.com/OctopusDeploy/go-octopusdeploy/pull/185

**Comment by csyme-cmc** [comment]
@benPearce1 and @slewis74 is there any further updates on this PR? Keen to have this fix implemented.

**Comment by benPearce1** [comment]
@csyme-cmc this has been merged and released in v2.21.0

**Comment by csyme-cmc** [comment]
Thanks @benPearce1 
Can you please bump the version in the Terraform provider and release a new version so this issue can be closed? https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/477

**Comment by benPearce1** [comment]
Apologies @csyme-cmc, this is now released as v0.10.3

**Pull request merged**
